logging:
  level:
    org.springframework.security: DEBUG
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:
            clientSecret:
          google:
            clientId:
            clientSecret:
